---
services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: statstag
      POSTGRES_USER: statstag
      POSTGRES_PASSWORD: statstag
    ports:
      - '5432:5432'
    volumes:
      - statstagpsql:/var/lib/postgresql/data
    profiles:
      - local

  postgresql-test:
    image: postgres:alpine
    environment:
      POSTGRES_DB: statstag
      POSTGRES_USER: statstag
      POSTGRES_PASSWORD: statstag
    ports:
      - '5432:5432'
    command:
      - postgres
      - -c
      - log_statement=all
    profiles:
      - test

volumes:
  statstagpsql:
