---
name: Terraform
on:
  push:
    branches:
      - master
    paths:
      - terraform/**/*
  pull_request:
    branches:
      - master
    paths:
      - terraform/**/*

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: 'true'
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check -recursive

  main:
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TF_IN_AUTOMATION: 'true'
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -input=false
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
          TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - run: terraform plan -input=false -out=prod.plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
          TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - run: terraform apply -input=false prod.plan
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}
          TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
